function hex = HEXColor(colorStr)
% Autogenerated 05-Apr-2011 17:41:19
% J. Gavornik

switch lower(colorStr) 
	case  lower('Snow')
		hex = 'FFFAFA';
	case  lower('Snow 2')
		hex = 'EEE9E9';
	case  lower('Snow 3')
		hex = 'CDC9C9';
	case  lower('Snow 4')
		hex = '8B8989';
	case  lower('Ghost White')
		hex = 'F8F8FF';
	case  lower('White Smoke')
		hex = 'F5F5F5';
	case  lower('Gainsboro')
		hex = 'DCDCDC';
	case  lower('Floral White')
		hex = 'FFFAF0';
	case  lower('Old Lace')
		hex = 'FDF5E6';
	case  lower('Linen')
		hex = 'F0F0E6';
	case  lower('Antique White')
		hex = 'FAEBD7';
	case  lower('Antique White 2')
		hex = 'EEDFCC';
	case  lower('Antique White 3')
		hex = 'CDC0B0';
	case  lower('Antique White 4')
		hex = '8B8378';
	case  lower('Papaya Whip')
		hex = 'FFEFD5';
	case  lower('Blanched Almond')
		hex = 'FFEBCD';
	case  lower('Bisque')
		hex = 'FFE4C4';
	case  lower('Bisque 2')
		hex = 'EED5B7';
	case  lower('Bisque 3')
		hex = 'CDB79E';
	case  lower('Bisque 4')
		hex = '8B7D6B';
	case  lower('Peach Puff')
		hex = 'FFDAB9';
	case  lower('Peach Puff 2')
		hex = 'EECBAD';
	case  lower('Peach Puff 3')
		hex = 'CDAF95';
	case  lower('Peach Puff 4')
		hex = '8B7765';
	case  lower('Navajo White')
		hex = 'FFDEAD';
	case  lower('Moccasin')
		hex = 'FFE4B5';
	case  lower('Cornsilk')
		hex = 'FFF8DC';
	case  lower('Cornsilk 2')
		hex = 'EEE8CD';
	case  lower('Cornsilk 3')
		hex = 'CDC8B1';
	case  lower('Cornsilk 4')
		hex = '8B8878';
	case  lower('Ivory')
		hex = 'FFFFF0';
	case  lower('Ivory 2')
		hex = 'EEEEE0';
	case  lower('Ivory 3')
		hex = 'CDCDC1';
	case  lower('Ivory 4')
		hex = '8B8B83';
	case  lower('Lemon Chiffon')
		hex = 'FFFACD';
	case  lower('Seashell')
		hex = 'FFF5EE';
	case  lower('Seashell 2')
		hex = 'EEE5DE';
	case  lower('Seashell 3')
		hex = 'CDC5BF';
	case  lower('Seashell 4')
		hex = '8B8682';
	case  lower('Honeydew')
		hex = 'F0FFF0';
	case  lower('Honeydew 2')
		hex = 'F4EEE0';
	case  lower('Honeydew 3')
		hex = 'C1CDC1';
	case  lower('Honeydew 4')
		hex = '838B83';
	case  lower('Mint Cream')
		hex = 'F5FFFA';
	case  lower('Azure')
		hex = 'F0FFFF';
	case  lower('Alice Blue')
		hex = 'F0F8FF';
	case  lower('Lavender')
		hex = 'E6E6FA';
	case  lower('Lavender Blush')
		hex = 'FFF0F5';
	case  lower('Misty Rose')
		hex = 'FFE4E1';
	case  lower('White')
		hex = 'FFFFFF';
	case  lower('Black')
		hex = '000000';
	case  lower('Dark Slate Gray')
		hex = '314F4F';
	case  lower('Dim Gray')
		hex = '696969';
	case  lower('Slate Gray')
		hex = '708A90';
	case  lower('Light Slate Gray')
		hex = '778899';
	case  lower('Gray')
		hex = 'BEBEBE';
	case  lower('Light Gray')
		hex = 'D3D3D3';
	case  lower('Midnight Blue')
		hex = '191970';
	case  lower('Navy')
		hex = '000080';
	case  lower('Cornflower Blue')
		hex = '6495ED';
	case  lower('Dark Slate Blue')
		hex = '483D8B';
	case  lower('Slate Blue')
		hex = '6A5ACD';
	case  lower('Medium Slate Blue')
		hex = '7B68EE';
	case  lower('Light Slate Blue')
		hex = '8470FF';
	case  lower('Medium Blue')
		hex = '0000CD';
	case  lower('Royal Blue')
		hex = '4169E1';
	case  lower('Blue')
		hex = '0000FF';
	case  lower('Dodger Blue')
		hex = '1E90FF';
	case  lower('Deep Sky Blue')
		hex = '00BFFF';
	case  lower('Sky Blue')
		hex = '87CEFA';
	case  lower('Light Sky Blue')
		hex = '87CEFA';
	case  lower('Steel Blue')
		hex = '4682B4';
	case  lower('Light Steel Blue')
		hex = 'B0C4DE';
	case  lower('Light Blue')
		hex = 'ADD8E6';
	case  lower('Powder Blue')
		hex = 'B0E0E6';
	case  lower('Prussian Blue')
		hex = '003153';
	case  lower('Pale Turquoise')
		hex = 'AFEEEE';
	case  lower('Dark Turquoise')
		hex = '00CED1';
	case  lower('Medium Turquoise')
		hex = '48D1CC';
	case  lower('Turquoise')
		hex = '40E0D0';
	case  lower('Cyan')
		hex = '00FFFF';
	case  lower('Light Cyan')
		hex = 'E0FFFF';
	case  lower('Cadet Blue')
		hex = '5F9EA0';
	case  lower('Medium Aquamarine')
		hex = '66CDAA';
	case  lower('Aquamarine')
		hex = '7FFFD4';
	case  lower('Dark Green')
		hex = '006400';
	case  lower('Dark Olive Green')
		hex = '556B2F';
	case  lower('Dark Sea Green')
		hex = '8FBC8F';
	case  lower('Sea Green')
		hex = '2E8B57';
	case  lower('Medium Sea Green')
		hex = '3CB371';
	case  lower('Light Sea Green')
		hex = '20B2AA';
	case  lower('Pale Green')
		hex = '98FB98';
	case  lower('Spring Green')
		hex = '00FF7F';
	case  lower('Lawn Green')
		hex = '7CFC00';
	case  lower('Chartreuse')
		hex = '7FFF00';
	case  lower('Medium Spring Green')
		hex = '00FA9A';
	case  lower('Green Yellow')
		hex = 'ADFF2F';
	case  lower('Lime Green')
		hex = '32CD32';
	case  lower('Yellow Green')
		hex = '9ACD32';
	case  lower('Forest Green')
		hex = '228B22';
	case  lower('Olive Drab')
		hex = '6B8E23';
	case  lower('Dark Khaki')
		hex = 'BDB76B';
	case  lower('Khaki')
		hex = 'F0E68C';
	case  lower('Pale Goldenrod')
		hex = 'EEE8AA';
	case  lower('Light Goldenrod Yellow')
		hex = 'FAFAD2';
	case  lower('Light Yellow')
		hex = 'FFFFE0';
	case  lower('Yellow')
		hex = 'FFFF00';
	case  lower('Gold')
		hex = 'FFD700';
	case  lower('Light Goldenrod')
		hex = 'EEDD82';
	case  lower('Goldenrod')
		hex = 'DAA520';
	case  lower('Dark Goldenrod')
		hex = 'B8860B';
	case  lower('Rosy Brown')
		hex = 'BC8F8F';
	case  lower('Indian Red')
		hex = 'CD5C5C';
	case  lower('Saddle Brown')
		hex = '8B4513';
	case  lower('Sienna')
		hex = 'A0522D';
	case  lower('Peru')
		hex = 'CD853F';
	case  lower('Burlywood')
		hex = 'DEB887';
	case  lower('Beige')
		hex = 'F5F5DC';
	case  lower('Wheat')
		hex = 'F5DEB3';
	case  lower('Sandy Brown')
		hex = 'F4A460';
	case  lower('Tan')
		hex = 'D2B48C';
	case  lower('Chocolate')
		hex = 'D2691E';
	case  lower('Firebrick')
		hex = 'B22222';
	case  lower('Brown')
		hex = 'A52A2A';
	case  lower('Dark Salmon')
		hex = 'E9967A';
	case  lower('Salmon')
		hex = 'FA8072';
	case  lower('Light Salmon')
		hex = 'FFA07A';
	case  lower('Orange')
		hex = 'FFA500';
	case  lower('Dark Orange')
		hex = 'FF8C00';
	case  lower('Coral')
		hex = 'FF7F50';
	case  lower('Light Coral')
		hex = 'F08080';
	case  lower('Tomato')
		hex = 'FF6347';
	case  lower('Orange Red')
		hex = 'FF4500';
	case  lower('Red')
		hex = 'FF0000';
	case  lower('Hot Pink')
		hex = 'FF69B4';
	case  lower('Deep Pink')
		hex = 'FF1493';
	case  lower('Pink')
		hex = 'FFC0CB';
	case  lower('Light Pink')
		hex = 'FFB6C1';
	case  lower('Pale Violet Red')
		hex = 'DB7093';
	case  lower('Maroon')
		hex = 'B03060';
	case  lower('Medium Violet Red')
		hex = 'C71585';
	case  lower('Violet Red')
		hex = 'D02090';
	case  lower('Violet')
		hex = 'EE82EE';
	case  lower('Plum')
		hex = 'DDA0DD';
	case  lower('Orchid')
		hex = 'DA70D6';
	case  lower('Medium Orchid')
		hex = 'BA55D3';
	case  lower('Dark Orchid')
		hex = '9932CC';
	case  lower('Dark Violet')
		hex = '9400D3';
	case  lower('Blue Violet')
		hex = '8A2BE2';
	case  lower('Purple')
		hex = 'A020F0';
	case  lower('Medium Purple')
		hex = '9370DB';
	case  lower('Thistle')
		hex = 'D8BFD8';
	otherwise
		warning('unknown colorStr ''%s''',colorStr);
		hex = '000000';
end