function triplet = RGBColor(colorStr)
% Autogenerated 05-Apr-2011 17:23:51
% J. Gavornik

switch lower(colorStr) 
	case  lower('Snow')
		triplet = [1.000000 0.980392 0.980392];
	case  lower('Snow 2')
		triplet = [0.933333 0.913725 0.913725];
	case  lower('Snow 3')
		triplet = [0.803922 0.788235 0.788235];
	case  lower('Snow 4')
		triplet = [0.545098 0.537255 0.537255];
	case  lower('Ghost White')
		triplet = [0.972549 0.972549 1.000000];
	case  lower('White Smoke')
		triplet = [0.960784 0.960784 0.960784];
	case  lower('Gainsboro')
		triplet = [0.862745 0.862745 0.862745];
	case  lower('Floral White')
		triplet = [1.000000 0.980392 0.941176];
	case  lower('Old Lace')
		triplet = [0.992157 0.960784 0.901961];
	case  lower('Linen')
		triplet = [0.941176 0.941176 0.901961];
	case  lower('Antique White')
		triplet = [0.980392 0.921569 0.843137];
	case  lower('Antique White 2')
		triplet = [0.933333 0.874510 0.800000];
	case  lower('Antique White 3')
		triplet = [0.803922 0.752941 0.690196];
	case  lower('Antique White 4')
		triplet = [0.545098 0.513725 0.470588];
	case  lower('Papaya Whip')
		triplet = [1.000000 0.937255 0.835294];
	case  lower('Blanched Almond')
		triplet = [1.000000 0.921569 0.803922];
	case  lower('Bisque')
		triplet = [1.000000 0.894118 0.768627];
	case  lower('Bisque 2')
		triplet = [0.933333 0.835294 0.717647];
	case  lower('Bisque 3')
		triplet = [0.803922 0.717647 0.619608];
	case  lower('Bisque 4')
		triplet = [0.545098 0.490196 0.419608];
	case  lower('Peach Puff')
		triplet = [1.000000 0.854902 0.725490];
	case  lower('Peach Puff 2')
		triplet = [0.933333 0.796078 0.678431];
	case  lower('Peach Puff 3')
		triplet = [0.803922 0.686275 0.584314];
	case  lower('Peach Puff 4')
		triplet = [0.545098 0.466667 0.396078];
	case  lower('Navajo White')
		triplet = [1.000000 0.870588 0.678431];
	case  lower('Moccasin')
		triplet = [1.000000 0.894118 0.709804];
	case  lower('Cornsilk')
		triplet = [1.000000 0.972549 0.862745];
	case  lower('Cornsilk 2')
		triplet = [0.933333 0.909804 0.803922];
	case  lower('Cornsilk 3')
		triplet = [0.803922 0.784314 0.694118];
	case  lower('Cornsilk 4')
		triplet = [0.545098 0.533333 0.470588];
	case  lower('Ivory')
		triplet = [1.000000 1.000000 0.941176];
	case  lower('Ivory 2')
		triplet = [0.933333 0.933333 0.878431];
	case  lower('Ivory 3')
		triplet = [0.803922 0.803922 0.756863];
	case  lower('Ivory 4')
		triplet = [0.545098 0.545098 0.513725];
	case  lower('Lemon Chiffon')
		triplet = [1.000000 0.980392 0.803922];
	case  lower('Seashell')
		triplet = [1.000000 0.960784 0.933333];
	case  lower('Seashell 2')
		triplet = [0.933333 0.898039 0.870588];
	case  lower('Seashell 3')
		triplet = [0.803922 0.772549 0.749020];
	case  lower('Seashell 4')
		triplet = [0.545098 0.525490 0.509804];
	case  lower('Honeydew')
		triplet = [0.941176 1.000000 0.941176];
	case  lower('Honeydew 2')
		triplet = [0.956863 0.933333 0.878431];
	case  lower('Honeydew 3')
		triplet = [0.756863 0.803922 0.756863];
	case  lower('Honeydew 4')
		triplet = [0.513725 0.545098 0.513725];
	case  lower('Mint Cream')
		triplet = [0.960784 1.000000 0.980392];
	case  lower('Azure')
		triplet = [0.941176 1.000000 1.000000];
	case  lower('Alice Blue')
		triplet = [0.941176 0.972549 1.000000];
	case  lower('Lavender')
		triplet = [0.901961 0.901961 0.980392];
	case  lower('Lavender Blush')
		triplet = [1.000000 0.941176 0.960784];
	case  lower('Misty Rose')
		triplet = [1.000000 0.894118 0.882353];
	case  lower('White')
		triplet = [1.000000 1.000000 1.000000];
	case  lower('Black')
		triplet = [0.000000 0.000000 0.000000];
	case  lower('Dark Slate Gray')
		triplet = [0.192157 0.309804 0.309804];
	case  lower('Dim Gray')
		triplet = [0.411765 0.411765 0.411765];
	case  lower('Slate Gray')
		triplet = [0.439216 0.541176 0.564706];
	case  lower('Light Slate Gray')
		triplet = [0.466667 0.533333 0.600000];
	case  lower('Gray')
		triplet = [0.745098 0.745098 0.745098];
	case  lower('Light Gray')
		triplet = [0.827451 0.827451 0.827451];
	case  lower('Midnight Blue')
		triplet = [0.098039 0.098039 0.439216];
	case  lower('Navy')
		triplet = [0.000000 0.000000 0.501961];
	case  lower('Cornflower Blue')
		triplet = [0.392157 0.584314 0.929412];
	case  lower('Dark Slate Blue')
		triplet = [0.282353 0.239216 0.545098];
	case  lower('Slate Blue')
		triplet = [0.415686 0.352941 0.803922];
	case  lower('Medium Slate Blue')
		triplet = [0.482353 0.407843 0.933333];
	case  lower('Light Slate Blue')
		triplet = [0.517647 0.439216 1.000000];
	case  lower('Medium Blue')
		triplet = [0.000000 0.000000 0.803922];
	case  lower('Royal Blue')
		triplet = [0.254902 0.411765 0.882353];
	case  lower('Blue')
		triplet = [0.000000 0.000000 1.000000];
	case  lower('Dodger Blue')
		triplet = [0.117647 0.564706 1.000000];
	case  lower('Deep Sky Blue')
		triplet = [0.000000 0.749020 1.000000];
	case  lower('Sky Blue')
		triplet = [0.529412 0.807843 0.980392];
	case  lower('Light Sky Blue')
		triplet = [0.529412 0.807843 0.980392];
	case  lower('Steel Blue')
		triplet = [0.274510 0.509804 0.705882];
	case  lower('Light Steel Blue')
		triplet = [0.690196 0.768627 0.870588];
	case  lower('Light Blue')
		triplet = [0.678431 0.847059 0.901961];
	case  lower('Powder Blue')
		triplet = [0.690196 0.878431 0.901961];
	case  lower('Prussian Blue')
		triplet = [0.000000 0.192157 0.325490];
	case  lower('Pale Turquoise')
		triplet = [0.686275 0.933333 0.933333];
	case  lower('Dark Turquoise')
		triplet = [0.000000 0.807843 0.819608];
	case  lower('Medium Turquoise')
		triplet = [0.282353 0.819608 0.800000];
	case  lower('Turquoise')
		triplet = [0.250980 0.878431 0.815686];
	case  lower('Cyan')
		triplet = [0.000000 1.000000 1.000000];
	case  lower('Light Cyan')
		triplet = [0.878431 1.000000 1.000000];
	case  lower('Cadet Blue')
		triplet = [0.372549 0.619608 0.627451];
	case  lower('Medium Aquamarine')
		triplet = [0.400000 0.803922 0.666667];
	case  lower('Aquamarine')
		triplet = [0.498039 1.000000 0.831373];
	case  lower('Green')
		triplet = [0.000000 1.000000 0.000000];
	case  lower('Dark Green')
		triplet = [0.000000 0.392157 0.000000];
	case  lower('Dark Olive Green')
		triplet = [0.333333 0.419608 0.184314];
	case  lower('Dark Sea Green')
		triplet = [0.560784 0.737255 0.560784];
	case  lower('Sea Green')
		triplet = [0.180392 0.545098 0.341176];
	case  lower('Medium Sea Green')
		triplet = [0.235294 0.701961 0.443137];
	case  lower('Light Sea Green')
		triplet = [0.125490 0.698039 0.666667];
	case  lower('Pale Green')
		triplet = [0.596078 0.984314 0.596078];
	case  lower('Spring Green')
		triplet = [0.000000 1.000000 0.498039];
	case  lower('Lawn Green')
		triplet = [0.486275 0.988235 0.000000];
	case  lower('Chartreuse')
		triplet = [0.498039 1.000000 0.000000];
	case  lower('Medium Spring Green')
		triplet = [0.000000 0.980392 0.603922];
	case  lower('Green Yellow')
		triplet = [0.678431 1.000000 0.184314];
	case  lower('Lime Green')
		triplet = [0.196078 0.803922 0.196078];
	case  lower('Yellow Green')
		triplet = [0.603922 0.803922 0.196078];
	case  lower('Forest Green')
		triplet = [0.133333 0.545098 0.133333];
	case  lower('Olive Drab')
		triplet = [0.419608 0.556863 0.137255];
	case  lower('Dark Khaki')
		triplet = [0.741176 0.717647 0.419608];
	case  lower('Khaki')
		triplet = [0.941176 0.901961 0.549020];
	case  lower('Pale Goldenrod')
		triplet = [0.933333 0.909804 0.666667];
	case  lower('Light Goldenrod Yellow')
		triplet = [0.980392 0.980392 0.823529];
	case  lower('Light Yellow')
		triplet = [1.000000 1.000000 0.878431];
	case  lower('Yellow')
		triplet = [1.000000 1.000000 0.000000];
	case  lower('Gold')
		triplet = [1.000000 0.843137 0.000000];
	case  lower('Light Goldenrod')
		triplet = [0.933333 0.866667 0.509804];
	case  lower('Goldenrod')
		triplet = [0.854902 0.647059 0.125490];
	case  lower('Dark Goldenrod')
		triplet = [0.721569 0.525490 0.043137];
	case  lower('Rosy Brown')
		triplet = [0.737255 0.560784 0.560784];
	case  lower('Indian Red')
		triplet = [0.803922 0.360784 0.360784];
	case  lower('Saddle Brown')
		triplet = [0.545098 0.270588 0.074510];
	case  lower('Sienna')
		triplet = [0.627451 0.321569 0.176471];
	case  lower('Peru')
		triplet = [0.803922 0.521569 0.247059];
	case  lower('Burlywood')
		triplet = [0.870588 0.721569 0.529412];
	case  lower('Beige')
		triplet = [0.960784 0.960784 0.862745];
	case  lower('Wheat')
		triplet = [0.960784 0.870588 0.701961];
	case  lower('Sandy Brown')
		triplet = [0.956863 0.643137 0.376471];
	case  lower('Tan')
		triplet = [0.823529 0.705882 0.549020];
	case  lower('Chocolate')
		triplet = [0.823529 0.411765 0.117647];
	case  lower('Firebrick')
		triplet = [0.698039 0.133333 0.133333];
	case  lower('Brown')
		triplet = [0.647059 0.164706 0.164706];
	case  lower('Dark Salmon')
		triplet = [0.913725 0.588235 0.478431];
	case  lower('Salmon')
		triplet = [0.980392 0.501961 0.447059];
	case  lower('Light Salmon')
		triplet = [1.000000 0.627451 0.478431];
	case  lower('Orange')
		triplet = [1.000000 0.647059 0.000000];
	case  lower('Dark Orange')
		triplet = [1.000000 0.549020 0.000000];
	case  lower('Coral')
		triplet = [1.000000 0.498039 0.313725];
	case  lower('Light Coral')
		triplet = [0.941176 0.501961 0.501961];
	case  lower('Tomato')
		triplet = [1.000000 0.388235 0.278431];
	case  lower('Orange Red')
		triplet = [1.000000 0.270588 0.000000];
	case  lower('Red')
		triplet = [1.000000 0.000000 0.000000];
	case  lower('Hot Pink')
		triplet = [1.000000 0.411765 0.705882];
	case  lower('Deep Pink')
		triplet = [1.000000 0.078431 0.576471];
	case  lower('Pink')
		triplet = [1.000000 0.752941 0.796078];
	case  lower('Light Pink')
		triplet = [1.000000 0.713725 0.756863];
	case  lower('Pale Violet Red')
		triplet = [0.858824 0.439216 0.576471];
	case  lower('Maroon')
		triplet = [0.690196 0.188235 0.376471];
	case  lower('Medium Violet Red')
		triplet = [0.780392 0.082353 0.521569];
	case  lower('Violet Red')
		triplet = [0.815686 0.125490 0.564706];
	case  lower('Violet')
		triplet = [0.933333 0.509804 0.933333];
	case  lower('Plum')
		triplet = [0.866667 0.627451 0.866667];
	case  lower('Orchid')
		triplet = [0.854902 0.439216 0.839216];
	case  lower('Medium Orchid')
		triplet = [0.729412 0.333333 0.827451];
	case  lower('Dark Orchid')
		triplet = [0.600000 0.196078 0.800000];
	case  lower('Dark Violet')
		triplet = [0.580392 0.000000 0.827451];
	case  lower('Blue Violet')
		triplet = [0.541176 0.168627 0.886275];
	case  lower('Purple')
		triplet = [0.627451 0.125490 0.941176];
	case  lower('Medium Purple')
		triplet = [0.576471 0.439216 0.858824];
	case  lower('Thistle')
		triplet = [0.847059 0.749020 0.847059];
	otherwise
		warning('unknown colorStr ''%s''',colorStr);
		triplet = [0 0 0];
end